project:
  type: website
  output-dir: ../docs

website:
  title: "Rømer Chain"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: pitch/index.qmd
        text: Pitch Deck
      - href: pop.qmd
        text: Proof of Physics
      - href: tokenomics.qmd
        text: Tokenomics
      - href: regions.qmd
        text: Regions
      - href: engineering.qmd
        text: Engineering
  
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true