project:
  type: website
  output-dir: ../docs

website:
  title: "Rømer Chain"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: pitch/index.qmd
        text: Pitch Deck
      - href: pop.qmd
        text: Proof of Physics
      - href: tokenomics.qmd
        text: Tokenomics
      - href: devnet.qmd
        text: Devnet
      - href: economics.qmd
        text: RØMER's Economic Model
      - href: validators.qmd
        text: Validators
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true