project:
  type: website
  output-dir: ../docs

website:
  title: "Rømer Chain"
  navbar:
    left:
      - text: Home
        href: index.qmd
      
      - text: Vision
        href: pitch/index.qmd
      
      - text: Tokenomics
        menu:
          - text: Overview
            href: economics/index.qmd
          - text: Economic Model
            href: economics/model.qmd
          - text: Token Distribution
            href: economics/distribution.qmd
          - text: Market Dynamics
            href: economics/market.qmd
          - text: Validator Economics
            href: economics/validators.qmd
      
      - text: Technical Design
        menu:
          - text: Architecture Overview
            href: technical/index.qmd
          - text: Proof of Physics
            href: technical/pop.qmd
          - text: Network Design
            href: technical/network.qmd
          - text: Development Roadmap
            href: technical/devnet.qmd
          - text: Validator Requirements
            href: technical/validators.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true